all:
	gcc -g ifdef.c test.c
	./a.out inp.txt out.txt name1

o:
	gcc -g ifdef.c test.c
	./a.out inp.txt out.txt name

1:
	gcc -g ifdef.c test.c
	./a.out inp.txt out.txt name1

vg1:
	gcc -g ifdef.c test.c
	valgrind ./a.out inp.txt out.txt name1
